config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/signup',   to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  get '/index-edit-basic-info', to: 'users#index_edit_basic_info', as: :index_basic_info 
  patch 'update-basic-info', to: 'users#update_basic_info'
  patch '/update_user_info', to: 'users#update_user_info' #ユーザー一覧からモーダル編集
  get 'users/duty', to: 'users#duty', as: :index_duty  #出勤中社員
  resources :bases do
  end
  # get 'bases', to: 'bases#index', as: :index_bases  #拠点一覧
  # post 'bases', to: 'bases#create'  #拠点新規作成
  # patch 'bases', to: 'bases#update' #拠点編集
  # delete 'bases', to: 'bases#destroy' #拠点削除
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  resources :users do
    resources :attendances, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
              format: {with: VALID_EMAIL_REGEX},
              uniqueness: {case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :department, length: { in: 3..50 }, allow_blank: true
  
  # 【勤怠B】No.9
  scope :get_by_name, ->(name){ where("name like ?", "%#{name}%") }
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update ]
  before_action :correct_user,   only: [:edit, :update ]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info ]
  before_action :general_user, only: [:index, :edit, :update, :show ]  #【勤怠B】追加機能〜一般ユーザーのアクセス制限〜

  def index
    @users = User.paginate(page: params[:page])
    if params[:name].present?  #【勤怠B】No.9
      @users = @users.get_by_name params[:name]
    end
  end
  
  def show
    @user = User.find(params[:id])
    @first_day = first_day(params[:first_day])
    @last_day = @first_day.end_of_month
    (@first_day..@last_day).each do |day|
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規登録に成功しました"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  # ユーザー一覧のモーダルから編集
  def update_user_info
    @user = User.find(params[:id])
    # if @user.update_attributes(users_all_info_params)
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新"
      redirect_to users_url
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to users_url
  end
  
  def edit_basic_info
    @user = User.find(params[:id])
  end
  
  # 【勤怠B】基本情報の編集専用画面
  def index_edit_basic_info
    @users = User.paginate(page: params[:page])
      if params[:name].present?  
        @users = @users.get_by_name params[:name]
      end
  end
  
  def update_basic_info
    @user = User.find(params[:id])
    if @user.update_attributes(basic_info_params)
      flash[:success] = "基本情報を更新しました"
      redirect_to @user
    else
      render 'edit_basic_info'
    end
  end
  
  # 出勤中社員一覧
  def duty
    @users = User.all
  end
  
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
      # params.require(:user).permit(:name, :email, :department, :employee_number, :uid, :basic_time, :work_time, :finish_work_time, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:basic_time, :work_time, :finished_at)
    end
    
    def users_all_info_params
      params.require(:user).permit(:name, :email, :department, :employee_number, :uid, :basic_time, :work_time, :finish_work_time, :password, :password_confirmation)
    end
  
    # ログイン済みか確認
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end

    # 正しいユーザーか？
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # 管理者かどうか？
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
    # 一般ユーザのアクセス制限
    def general_user
      unless current_user.admin?
        @user = User.find(params[:id])
          redirect_to(root_url) unless current_user?(@user)
      end
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
    def format_basic_time(datetime) 
        format("%.2f", ((datetime.hour * 60) + datetime.min)/60.0)
    end
    
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :department %> 
  <%= f.text_field :department, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <section>
    
  <%= user.name %><br>
    <% if current_user.admin? %>
      <% unless user.admin %> <!--管理者の削除は不要-->
        <%= link_to "削除", user, method: :delete, class: "btn btn-primary", data: {confirm: "削除してよろしいですか？"} %>
      <% end %>
    <div class="panel-group">
      <div class="panel panel-default">
        <div class="panel-heading">
          <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#edit<%= user.id %>">編集</button>
        </div>
        <div id="edit<%= user.id %>" class="collapse panel-collapse">
          <div class="panel-body ">
            <h3>アカウント情報の更新</h3>
            <%= form_for(user, url: update_user_info_path(user), method: :patch) do |af| %>    <!--url: update_user_info_path(params: {id: user.id}) を足したい-->
            <!--名前のフォーム-->      
              <%= af.label :name %>
              <%= af.text_field :name, class: 'form-control' %>
            <!--メールのフォーム--> 
              <%= af.label :email %>
              <%= af.email_field :email, class: 'form-control' %>
            <!--部署のフォーム--> 
              <%= af.label :department %>
              <%= af.text_field :department, class: 'form-control' %>
            <!--社員番号のフォーム--> 
              <%= af.label :employee_number %>
              <%= af.text_field :employee_number, class: 'form-control' %>
            <!--カード番号のフォーム--> 
              <%= af.label :uid %>
              <%= af.text_field :uid, class: 'form-control' %>
              
              <% unless user.admin %> <!--【基本情報】管理者以外のフォーム--> 
                <!--基本時間のフォーム--> 
                  <%= af.label :basic_time %>
                  <%= af.time_field :basic_time, class: 'form-control' %>
                <!--指定勤務開始時間のフォーム--> 
                  <%= af.label :work_time %>
                  <%= af.time_field :work_time, class: 'form-control' %>
                <!--指定勤務終了時間のフォーム--> 
                  <%= af.label :finish_work_time %>
                  <%= af.time_field :finish_work_time, class: 'form-control' %>  
              <% end %>
              
            <!--パスワードのフォーム--> 
              <%= af.label :password %>
              <%= af.password_field :password, class: 'form-control' %>
            <!--パスワード確認のフォーム--> 
              <%= af.label :password_confirmation %>
              <%= af.password_field :password_confirmation, class: 'form-control' %>  
              <%= af.submit "更新", class: "btn btn-primary" %>
            <% end %>
          </div><!--panel-body終わり--> 
        </div><!--collapse panel-collapse-->
      </div><!--panel panel-default終わり--> 
    </div><!--panel-group終わり--> 
  <% end %>  
  </section>
</li>

app/views/users/duty.html.erb
<% provide(:title, '出勤中社員一覧') %>
<h1>出勤中社員一覧</h1>

<div>
  <table class = "table-bordered table-condensed">
    <tr>
      <th>社員番号</th>
      <th>名前</th>
    </tr>
    
    <% @users.each do |user| %>
      <% user.attendances.each do |attendance| %>
        <% if attendance.started_at.present? && attendance.finished_at.nil? && attendance.worked_on == Date.today %> <!--出勤中の社員-->
          <tr>
            <td><%= user.employee_number %></td>
            <td><%= user.name %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </table>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'アカウント編集') %>
<% provide(:button_text, '更新する') %>
<h1>アカウント情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報編集") %>

<h1>基本情報の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: update_basic_info_path(params: {id: @user.id})) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :basic_time %>
      <%= f.time_field :basic_time, class: 'form-control' %>

      <%= f.label :work_time %>
      <%= f.time_field :work_time, class: 'form-control' %>

      <%= f.submit "更新する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '一覧') %>
<h1>ユーザー一覧</h1>

<div class="head-form">
  <!--CSVインポート-->
  <div class="csv-import col-sm-4">
    <%= form_tag(users_path, method: :get) %>
    <%= file_field_tag :name  %>
    <%= submit_tag "CSVをインポート", class: "btn btn-primary col-sm-6" %><br><br>
  </div>
  
  <!--【勤怠B】No.9　検索-->
  <div class="user-search col-sm-4">
    <h4>ユーザー検索</h4>
    <%= form_tag(users_path, method: :get) %>
    <%= text_field_tag :name, params[:name], placeholder: "キーワードを入力…", class: 'form-control col-sm-2' %>
    <%= submit_tag "検索", class: "btn btn-primary col-sm-2" %>
  </div>
</div>

<%= will_paginate @users, :previous_label => '&lt 前へ', :next_label => '次へ &gt' %>  <!--【勤怠B】No.5-->

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate @users, :previous_label => '&lt 前へ', :next_label => '次へ &gt' %>  <!--【勤怠B】No.5-->

app/views/users/index_edit_basic_info.html.erb
<% provide(:title, '一覧') %>
<h1>基本情報の修正</h1>

<!--【勤怠B】No.9-->
<div class="user-search col-sm-4">
  <h4>ユーザー検索</h4>
  <%= form_tag(users_path, method: :get) %>
  <%= text_field_tag :name, params[:name], placeholder: "キーワードを入力…", class: 'form-control col-sm-2' %>
  <%= submit_tag "検索", class: "btn btn-primary col-sm-2" %>
</div>

<%= will_paginate @users, :previous_label => '&lt 前へ', :next_label => '次へ &gt' %>  <!--【勤怠B】No.5-->

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name , user %>
      <% if current_user.admin? %>
        | <%= link_to "基本情報の編集", basic_info_path(user) %>
      <% end %>
    </li>
  <% end %>

</ul>

<%= will_paginate @users, :previous_label => '&lt 前へ', :next_label => '次へ &gt' %>  <!--【勤怠B】No.5-->

app/views/users/new.html.erb
<% provide(:title, '新規作成') %>
<% provide(:button_text, '作成する') %>
<h1>ユーザー作成</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, '勤怠表示') %>
<div>
  <table class = "table-bordered table-condensed">
    <tr>
      <td>
        <%= link_to "←", user_path(params: {id: @user.id, first_day: @first_day.prev_month }),
                         class: "btn btn-xs btn-primary" %>
        &emsp;<%= @first_day.to_s(:year_month) %>　時間管理表&emsp;
        <%= link_to "→", user_path(params: {id: @user.id, first_day: @first_day.next_month }),
                         class: "btn btn-xs btn-primary" %>
      </td>
      <td>
        指定勤務時間 <%= format_basic_time(@user.work_time) %><br>
        指定勤務終了時間 <%= format_basic_time(@user.finish_work_time) %> 
      </td>
      <td colspan="2">基本時間 <%= format_basic_time(@user.basic_time) %></td>
      <td>初日 <%= @first_day.to_s(:date) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未設定" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>コード：<%= @user.uid %></td>
      <td>出勤日数<%= @worked_sum %></td>
      <td>締日　<%= @last_day.to_s(:date) %></td>
    </tr>
  </table>
    
  <!--【上長】承認申請-->
  <% if current_user.superior? %>
  <!--多分、ifデータがある時とでリンクを分岐させる-->
    <p>所属長承認申請のお知らせ</p>
    <p>勤怠変更申請のお知らせ</p>
    <p>残業申請のお知らせ</p>
  <% end %>
    
  <%= link_to "勤怠を編集", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %>
  <%= link_to "CSV出力", user_path(format: :csv), class: "btn btn-primary" %>
  <%= link_to "勤怠修正ログ（承認済み）", "#", class: "btn btn-primary" %>
    
  <table class= "table-bordered table-striped table-condensed">
    <thead>
      <tr>
        <th rowspan = "3">残業申請</th>
        <th rowspan = "3">日付</th>
        <th rowspan = "3">曜日</th>
        <th colspan = "8">実績</th>
        <th colspan = "7">所定外勤務</th>
      </tr>
      <tr>
        <th colspan = "3">出社</th>
        <th colspan = "3">退社</th>
        <th rowspan = "2">在社時間</th>
        <th rowspan = "2">備考</th>
        <th colspan = "2">終了予定時間</th>
        <th rowspan = "2">時間外時間</th>
        <th rowspan = "2">業務処理内容</th>
        <th rowspan = "2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
        
    <tbody>
      <% @dates.each do |day| %>
      <tr>
        <td> <!--残業申請ボタン-->
          <button type="button" class="btn btn-primary" data-toggle="modal" 
            data-target="#sampleModal" 
            data-date="<%= day.worked_on.to_s(:date) %>" 
            data-week="<%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %>">
          残業申請
          </button>
        
          <div class="modal fade" id="sampleModal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
        　　　　　　<!--モーダルを閉じる×ボタンを作る-->
                  <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                    <span aria-hidden="true">&times;</span>
                  </button>
        　　　　　　<!--モーダルのタイトル-->
                  <h4 class="modal-title" id="Modal">残業申請</h4>
                 </div>  <!--modal-header終わり-->
                 <div class="modal-body">
                 <table class="table table-bordered table-striped table-condensed">
                   <tr>
                     <th>日付</th>
                     <th>曜日</th>
                     <th>終了予定時間</th>
                     <th>翌日</th>
                     <th>業務処理内容</th>
                     <th>指示者確認㊞</th>
                   </tr>
                   
                   <tr>
                     <td class="modal-date"></td>
                     <td class="modal-week"></td>
                     <td>終了予定時間</td>
                     <td>翌日</td>
                     <td>業務処理内容</td>
                     <td>指示者確認㊞</td>
                   </tr>
                 </table>
                 </div>  <!--modal-body終わり-->
         
                 <div class="modal-footer">
                   <!--モーダルを閉じるボタン-->
                   <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                 </div>  <!--modal-footer終わり-->
                 
              </div>
            </div>
          </div>  
          
       <script>
          // ボタンがクリックされてモーダルが開いたら作動
          $('#sampleModal').on('show.bs.modal', function (event) { 
          // クリックされたbuttonを取得
          var button = $(event.relatedTarget); 
          // 上記の中の、data-date, data-week の値を取得
          var date = button.data('date'); 
          var week = button.data('week');
          // クリックされているsampleModal要素を取得
          var modal = $(this); 
                        
          // sampleModalの中のmodal-date,modal-weekという要素を取得し、そこにdata-dateの値を入れる。これでクリックした日付の日付がモーダル内に入る
          modal.find('.modal-date').text(date);
          modal.find('.modal-week').text(week);
          });
        </script>            
        </td>
        <!--残業申請ボタン終わり-->
        <td><%= day.worked_on.to_s(:date) %></td>
        <td>
          <% if %w{日 月 火 水 金 木 土}[day.worked_on.wday] == "土" %>  <!--【勤怠B】No.1-->
              <font color ="blue"><%= %w{日 月 火 水 金 木 土}[day.worked_on.wday] %><font>
          <% elsif %w{日 月 火 水 金 木 土}[day.worked_on.wday] == "日" %>  <!--【勤怠B】No.1-->
              <font color ="red"><%= %w{日 月 火 水 金 木 土}[day.worked_on.wday] %><font>
          <% else %>
              <%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %>
          <% end %>
        </td>
        <td><%= day.started_at.to_s(:hour) if day.started_at.present? %></td>
        <td><%= day.started_at.floor_to(60*15).to_s(:min) if day.started_at.present? %></td>
        <td>
          <% if day.worked_on == Date.today && day.started_at.nil? %>
              <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
          <% end %>
        </td>
        <td><%= day.finished_at.to_s(:hour) if day.finished_at.present? %></td>
        <td><%= day.finished_at.floor_to(60*15).to_s(:min) if day.finished_at.present? %></td>
        <td>
          <% if day.worked_on == Date.today && day.started_at.present? && day.finished_at.nil? %>
            <%= button_to "退勤", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
          <% end %>
        </td>
        <td>
          <% if day.started_at.present? && day.finished_at.present? %>
            <%= working_times(day.started_at, day.finished_at) %>
            <% seconds = (day.finished_at - day.started_at).to_i %>
            <% @total_seconds = @total_seconds.to_i + seconds %>
          <% end %>
        </td>
        <td><%= day.note %></td>
        <td><%= day.started_at.to_s(:hour) if day.started_at.present? %></td> <!--要変更　終了予定【時】-->
        <td><%= day.started_at.floor_to(60*15).to_s(:min) if day.started_at.present? %></td> <!--要変更　終了予定【分】-->
        <td></td> <!--要変更　時間外-->
        <td><%= day.note %></td> <!--要変更　業務処理内容-->
        <td></td> <!--要変更　指示者確認-->
      </tr>
      <% end %>
    </tbody>
      
    <tfoot>
      <tr>
        <td colspan = "3"><%= format_basic_time(@user.basic_time).to_f * @worked_sum %></td>
        <td colspan = "6"></td>
        <td><%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>
          <%= form_for @user do |f| %>
            <%= f.collection_select :name, User.where(superior: true), :name, :name %>
            <%= f.submit "申請", class: "btn btn-primary" %>
          <% end %>
        </td>
      </tr>
    </tfoot>
  </table>
</div>