config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/signup',   to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  get '/index-edit-basic-info', to: 'users#index_edit_basic_info', as: :index_basic_info 
  patch 'update-basic-info', to: 'users#update_basic_info'
  patch '/update_user_info', to: 'users#update_user_info' #ユーザー一覧からモーダル編集
  get 'users/duty', to: 'users#duty', as: :index_duty  #出勤中社員
  resources :bases do
  end
  # get 'bases', to: 'bases#index', as: :index_bases  #拠点一覧
  # post 'bases', to: 'bases#create'  #拠点新規作成
  # patch 'bases', to: 'bases#update' #拠点編集
  # delete 'bases', to: 'bases#destroy' #拠点削除
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  resources :users do
    resources :attendances, only: :create
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "勤怠管理システム", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップへ", root_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "ユーザ一覧", users_path %></li>
            <li><%= link_to "出勤社員一覧", index_duty_path %></li>
            <li><%= link_to "地点情報一覧修正", bases_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                アカウント <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "ユーザー勤怠情報表示", current_user %></li>
                <li><%= link_to "設定",  edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザー勤怠情報表示", current_user %></li>
              <li><%= link_to "設定",  edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
            </ul>
          <% end %>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>  
          <div class="alert alert-<%= message_type %>">
            <%= message %>
          </div>
        <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>